### ISSUE TITLE
Routes= lost after link drop

### ISSUE THREAD

**Issue by pheew** [joukewitteveen/netctl#108]
Not sure if this is the right place to ask but here goes. I use netctl to manage the following interfaces on a router:

```
(physical nic)          (vlan 4)                 (macvlan)
net_wan --------->   iptv_vlan ---------> iptv
     \       
      \         (vlan 34)
       >       internet
```

netctl config is here: https://gist.github.com/pheew/05de22193e4146685078

When the system boots all is fine. The Routes= from the iptv config file are added as expected. The resulting routing table as follows is correct:

```
$ ip route
default via 82.197.212.1 dev internet  metric 207 
10.0.0.0/16 dev net_lan  proto kernel  scope link  src 10.0.0.1 
10.10.28.0/22 dev iptv  proto kernel  scope link  src 10.10.30.103  metric 210 
82.197.212.0/24 dev internet  proto kernel  scope link  src 82.197.212.111  metric 207 
185.6.48.0/26 via 10.10.28.1 dev iptv 
```

Whenever the parent interface (net_wan) looses its link and comes back up the iptv will be restored but will loose the route specified in Routes=

```
$ ip route
default via 82.197.212.1 dev internet  metric 207 
10.0.0.0/16 dev net_lan  proto kernel  scope link  src 10.0.0.1 
10.10.28.0/22 dev iptv  proto kernel  scope link  src 10.10.30.103  metric 210 
82.197.212.0/24 dev internet  proto kernel  scope link  src 82.197.212.111  metric 207 
```

Could it be that the route is discarded by a running dhcpcd instance maybe?
I've also tried to remedy the issue by using ifplugd to reapply the netctl profile but that had the same result.

```
$ sudo systemctl enable netctl-ifplugd@iptv.service
```

I can restore the route by manually stopping/starting with:

```
$ sudo netctl stop iptv
$ sudo netctl start iptv
```

but i'd much rather have this done automatically.

**Comment by joukewitteveen** [comment]
Any news on this? Is this still an issue?

**Comment by pheew** [comment]
No sorry, no news. I'm using CentOS on the router now.

**Comment by joukewitteveen** [comment]
Possibly a bug with dhcpcd.
