### ISSUE TITLE
IPv4LL not supported. IPv4LL should be supported

### ISSUE THREAD

**Issue by ozgurkeles** [joukewitteveen/netctl#109]
your code "src/lib/dhcp/dhcpcd" at line 
line:6 seems like 
<code> 
4) options="$DhcpcdOptions -L";;
</code>
if i change the code to 
<code>
4) options="$DhcpcdOptions";;
</code>
and change configuration file "/etc/dhcpcd.conf"  <code> noipv4ll </code> to <code> #noipv4ll </code>
its worked

**Comment by joukewitteveen** [comment]
Why and how do you think IPv4LL should be supported? I do not want to use it by default as it makes failure harder to detect when connecting.

**Comment by ozgurkeles** [comment]
This is for getting automatic ip at small doesnt support DHCP network
it shouldnt be default can be parametric

**Comment by LukeShu** [comment]
The `-L` flag is shorthand for `--noipv4ll` which forcefully disables IPv4LL; if the flag is removed then IPv4LL would be perfectly supported.  Perhaps having IPv4LL disabled by default is the correct decision, but there should be a way to override that default and enable it.  But, I still don't believe that netctl should push a default for IPv4LL; it is already disabled by default in `/etc/dhcpcd.conf` (at least on Arch Linux), removing the `-L` flag in netctl will only enable it if the user has already taken manual steps to enable it.

**Comment by joukewitteveen** [comment]
The next version will allow support for IPv4LL via dhcpcd. Note that it is currently already supported through dhclient using avahi-autoipd.

Support for IPv4LL with dhcpcd is implemented by turning "-L" into a proper default value of `DhcpcdOptions=`. Thus by specifying an empty value to that variable in your profile, the default value is overridden and support for IPv4LL is not disabled. 6c29ab4f88e40adee66277f635d84c633fa2873b
