### ISSUE TITLE
netctl cannot start this because the interface is already up

### ISSUE THREAD

**Issue by taylorchu** [joukewitteveen/netctl#11]
this happens a lot for me. netctl simply exits, and i dont think this behavior is right.

**Comment by MauroMombelli** [comment]
Hello, arch Linux on raspi here. Something is keeping my eth0 up ( if I try to put it down it say it does not support remote shutdown and immediately bring it up). Using force connect is a working workaround, but...

**Comment by reggaedit** [comment]
Just commenting in case anyone else comes here. Adding 'ForceConnect=yes' to my eduroam profile worked for me. I tried countless other things, and I had the same errors as above. Really not sure what was wrong with my computer.

**Comment by mervin0502** [comment]
I have fixed this problem by the wiki

> Job for netctl@wlan(...).service failed
> Warning: This section assumes that there is no other network service running before starting a netctl profile/service. See #Installation for details.
> Some people have an issue when they connect to a network with netctl, for example:
> # netctl start wlan0-ssid
> Job for netctl@wlan0\x2ssid.service failed. See 'systemctl status netctl@wlan0\x2ssid.service' and 'journalctl -xn' for details.
> When then looking at journalctl -xn, either of the following are shown:
> 1. If your device (wlan0 in this case) is up:
> network[2322]: The interface of network profile 'wlan0-ssid' is already up
> Setting the interface down should resolve the problem:
> # ip link set wlan0 down
> Then retry:
> # netctl start wlan0-ssid
> 2. If the error continues, try again after adding the ForceConnect option:
> /etc/netctl/wlan0-ssid

> 
> ...
> ForceConnect=yes
> Save it and try to connect with the profile:
> # netctl start wlan0-ssid
>
