### ISSUE TITLE
`netctl status` w/o profile displays status of all active profiles

### ISSUE THREAD

**Issue by zfjagann** [joukewitteveen/netctl#110]
It would be nice to list the status of all the profiles that are currently in use.

Here's a really simple [bash script](https://gist.github.com/zfjagann/d875b125a1318bef5db8) that does essentially what I want. It'd be nice if it was incorporated into netctl somehow.

**Comment by joukewitteveen** [comment]
do you have a use case for this?

**Comment by zfjagann** [comment]
The most common use case for me is examining network connections at a glance. `netctl list` will show you which network profiles are active, but this can be misleading, since this doesn't actually mean they are working. For example, dhcpcd frequently fails on my box do to an unrelated issue, which causes `netctl list` to display it as being active, but `netctl status` to display it as having failed.

Another possibility would be to display some kind of status indicator in the output of `netctl list` along with the asterisk. The asterisk would indicate which profiles are in use, and a different icon, or column could indicate which profiles are actually working.

**Comment by joukewitteveen** [comment]
I would consider patches that implement more advanced status symbols in `netctl list`, but, honestly, I think failure of, say, dhcpcd should propagate and result in a profile that is down.
