### ISSUE TITLE
Bug with the new version of wpa_supplicant

### ISSUE THREAD

**Issue by TheCrafter** [joukewitteveen/netctl#112]
I just installed arch linux and downloaded the latest version of wpa_supplicant to run wifi-menu. After running wifi-menu, I wait 2-3 seconds and I get "Abort".

I do know why is that happening. Here, take a look at a recent, relevant post on reddit.
http://www.reddit.com/r/archlinux/comments/33s2hk/wifimenu_and_netctl_not_working/

**Comment by foutrelis** [comment]
Please test if `wifi-menu` works after editing `/usr/lib/network/wpa` as shown here: https://github.com/foutrelis/netctl/commit/f87ee53ca82e270e6d3cbea8e5672b068e450d79.

**Comment by TheCrafter** [comment]
Yes it worked. `wifi-menu` works fine now. Thanks for your response.

**Comment by foutrelis** [comment]
Please reopen the issue if you can; that patch hasn't been merged yet.

**Comment by TheCrafter** [comment]
I apologize, I did not know that. You close the issue whenever you feel appropriate.
