### ISSUE TITLE
Provide a way to specify global wpa_supplicant options other than 'Country'

### ISSUE THREAD

**Issue by trustin** [joukewitteveen/netctl#114]
`wpa_make_config_file()` at `/usr/lib/network/wpa` produces the header part of the configuration file for `wpa_supplicant`.  It currently adds the `Country` option from the interface configuration at `/etc/netctl/interfaces` to the generated header but nothing else.  For instance, I want to add the options such as `autoscan=exponential:2:30` and `interworking=0`, but it seems like there's no proper way to do that.

As a workaround, I did the hack like the following:

```
Country="JP
interworking=0
autoscan=exponential:2:30
"
```

.. but I wish there's a better way to specify global wpa_supplicant options.

**Comment by joukewitteveen** [comment]
Unless options are very common, I think it is best to resort to `WPAConfigSection=` or `WPAConfigFile=` for advanced option needs.

**Comment by trustin** [comment]
`WPAConfigSection` does not allow you to specify a global option. `WPAConfigFile` is a showstopper because it's impossible to use `netctl-auto` with it. Please consider reopening this issue and solving it properly.

**Comment by trustin** [comment]
I can also come up with a PR that fixes this issue if you are fine.

**Comment by joukewitteveen** [comment]
Your options would be ignored by netctl-auto anyway, precisely because they are global. Is that not a problem?
