### ISSUE TITLE
Wifi not connecting...

### ISSUE THREAD

**Issue by AndrieVorster** [joukewitteveen/netctl#118]
Hi, I am using a Mecer/Mustek laptop and I cannot connect to Wifi.
Since I have no Internet connection I am posting this screenshots... Via my Mothers Laptop.
The current driver (ipw2200-fw) is installed and up to date... I think this is a systemd problem.

I am using netclt/wifi-menu...
`wifi-menu -o`

Here I try to connect to our Wifi Router (my phone, Mothers laptop etc. is connected, so it's working).
`journald -xe`
[Wifi Router.]
(https://drive.google.com/file/d/0B4QLBt770Wyuc01mTVJ1dHRIc2M/view?usp=sharing)

Here I try to connect to my phones Wifi Hotspot with no success as well (my Mothers laptop can connect to it, so it's working).
`journald -xe`
[Phone Hotspot.]
(https://drive.google.com/file/d/0B4QLBt770WyuN0x4bFlsWW52VVk/view?usp=sharing)

Regards,
And thanks,
Andrie Vorster.

P.S. I am using Manjaro Linux with Kernel 3.18 or 4.1.... Neither of them are working.

**Comment by joukewitteveen** [comment]
It looks like you are trying to use multiple network managers. Use either NetworkManager or netctl (or any other manager), but not both.

**Comment by AndrieVorster** [comment]
I haven't installed anything all is default... Sorry for the trouble I will try and find out more on their Wiki and Forum!
