### ISSUE TITLE
ip4ip6 tunnel does not work

### ISSUE THREAD

**Issue by RubenKelevra** [joukewitteveen/netctl#119]
My config:

Description='ip4ip6 to tunnel he'
Interface=tun-he6
Connection=tunnel
Mode=ip4ip6
Remote='216.66.84.54'
Local='62.141.34.115'

IP6=static
Address6='2001:470:12:11d::2/64'

When I try to start it the following error occour:

Okt 06 12:16:30 rig.freifunk-nrw.de systemd[1]: Starting Networking for netctl profile tun-he6...
Okt 06 12:16:30 rig.freifunk-nrw.de network[24249]: Starting network profile 'tun-he6'...
Okt 06 12:16:30 rig.freifunk-nrw.de network[24249]: Error: an inet prefix is expected rather than "216.66.84.54".
Okt 06 12:16:30 rig.freifunk-nrw.de network[24249]: Failed to bring the network up for profile 'tun-he6'

**Comment by joukewitteveen** [comment]
Does it work if you change line 15 of `/usr/lib/network/connections/tunnel` to
```
    [[ $Mode == ip6* || $Mode == "any" ]] && family="-6"
```
(note the missing `*` before `ip6`)?

**Comment by joukewitteveen** [comment]
Is this supposed to work? All examples I find on-line use an IPv6 remote address...

**Comment by RubenKelevra** [comment]
Well sorry, please close this bug as invalid.
