### ISSUE TITLE
Specifiying multiple bond devices with different attributes

### ISSUE THREAD

**Issue by grpomega** [joukewitteveen/netctl#120]
Cannot configure multiple bond interfaces through /etc/modprobe.d/bonding.conf
will only honour last config listed in bonding.conf
does not seem to honour alias directive in bonding.conf

bonding driver seems to only accept mode and miimon parameters from the command line?!?

gave up and decided to set parameters through sysfs interface
I don't know if the best test for sysfs is the presence of the /sys/class/net directory
Nor why the existing code for setting the mode the Mode does not seem to work 
>interface_add bond "$Interface" "" ${Mode:+mode "$Mode"}
on the first iteration through 
the next line in the code below sets the mode- using the additional "$mode" variable

if the below general solution is acceptable I will make it a pull request
Cannot configure multiple bond interfaces through /etc/modprobe.d/bonding.conf
will only honour last config listed in bonding.conf
does not seem to honour alias directive in bonding.conf

bonding driver seems to only accept mode and miimon parameters from the command line?!?

gave up and decided to set parameters through sysfs interface
I don't know if the best test for sysfs is the presence of the /sys/class/net directory
Nor why the existing code for setting the mode the Mode does not seem to work

    interface_add bond "$Interface" "" ${Mode:+mode "$Mode"}
    on the first iteration through
    the next line in the code below sets the mode- using the additional "$mode" variable

if the below general solution is acceptable I will make it a pull request

**Comment by grpomega** [comment]
Cannot configure multiple bond interfaces through /etc/modprobe.d/bonding.conf
will only honour last config listed in bonding.conf
does not seem to honour alias directive in bonding.conf

bonding driver seems to only accept mode and miimon parameters from the command line?!?

gave up and decided to set parameters through sysfs interface
I don't know if the best test for sysfs is the presence of the /sys/class/net directory
Nor why the existing code for setting the mode the Mode does not seem to work

    interface_add bond "$Interface" "" ${Mode:+mode "$Mode"}
    on the first iteration through
    the next line in the code below sets the mode- using the additional "$mode" variable

if the below general solution is acceptable I will make it a pull request
```
bond_up() {
#echo "${BindsToInterfaces[@]} $Mode 5" > /root/dump
    if is_interface "$Interface"; then
#echo "$Interface 6" >> /root/dump
        report_error "Interface '$Interface' already exists"
        return 1
    fi

    interface_add bond "$Interface" "" ${Mode:+mode "$Mode"}
    #does not seem to honor $Mode -- have to set mode before interfaces are enslaved
    if [ -n "$mode" ]
     then
     echo "$mode" >/sys/class/net/$Interface/bonding/mode
     fi
    bring_interface_up "$Interface"
    for slave in "${BindsToInterfaces[@]}"; do
        ip link set dev "$slave" master "$Interface"
    done

    if [ -d /sys/class/net ]
     then
     #all array type values here
     for var in arp_ip_target
      do
      list="$var[@]"
      for member in ${!list}
       do
       echo +$member>/sys/class/net/$Interface/bonding/$var
       done
      done

     #all single value options execpt for mode
     for var in active_slave ad_actor_key ad_aggregator ad_num_ports ad_partner_key ad_partner_mac ad_select all_slaves_active arp_interval arp_validate downdelay fail_over_mac lacp_rate lp_interval mii_status miimon min_links num_grat_arp num_unsol_na packets_per_slave primary primary_reselect queue_id resend_igmp slaves tlb_dynamic_lb updelay use_carrier xmit_hash_policy
      do
      val=${!var}
      if [ -n "$val" ]
       then
       echo "$val" >/sys/class/net/$Interface/bonding/$var
       fi
      done
     fi

    ip_set
}

```

**Comment by joukewitteveen** [comment]
This is rather incomprehensible. What is the problem precisely?

**Comment by grpomega** [comment]
Sorry
I am on netctl-1.11-1 in arch linux
I want to establish multiple bonded circuits with different parameters
the parameters offered through netctl are limited to Mode which is not sufficient for my requirements

I tried the various suggestions without success:
1. create and modify modprobe.d/bonding.conf with aliases for the different interfaces
2. directly load driver with required parameters

After these seemed to fail for the reasons above, I inspected the code and saw that it would be simple to modify netctl to bring up the bond interface with the required parameters.

I have modified the /lib/network/connections/bond - bond_up() to recognize the other bond driver parameters.

I have a couple of questions before I submit a pull request
1.  setting the mode through
`interface_add bond "$Interface" "" ${Mode:+mode "$Mode"}`
does not seem to work -  I had always had a bonding.conf file with the mode.  It comes up as mode=0 when this is set.
Work around was to set it in the next code block through sysfs

2. do you think this method of detecting sysfs is sufficient for production code?
`if [ -d /sys/class/net ]`

**Comment by joukewitteveen** [comment]
This is subsumed in #128. Two bugs appear to be present here:

1) The bond0 interface is automatically created when the bonding module is loaded
This behavior of the kernel is quite unfortunate for `netctl` and there appears to be no fix for `netctl` that is not essentially a workaround. Adding max_bonds=0 to the loading parameters of the bonding module prevents bond0 from being created. This is the cleanest solution, but outside the scope of `netctl`.

2) The bonding and bridging connection types (and possibly others) lack certain parameters. They should be added one by one similar to how `mode` is currently handled in `src/lib/connections/bond`. Pull requests are welcome. Parameters that are maybe too obscure for `netctl` can be added via `LinkOptions=` since eaeacf18db25b072b32bd0c7ed41c8ae6c0b579c.

**Comment by k0ste** [comment]
@joukewitteveen 

`ip link add bond0 type bond mode 802.3ad miimon 100 lacp_rate 1 xmit_hash_policy layer2+3` > `RTNETLINK answers: File exists`, i.e. this options not work. Yes, this is not netctl problem.

To not do so - adding `max_bonds=0` to loading parameters may be avoid this problem with **bond0** via set `ip link set bond0 type bond mode 802.3ad miimon 100 lacp_rate 1 xmit_hash_policy layer2+3` after  `interface_add()`?
