### ISSUE TITLE
netctl-ifplugd problem with removable ethernet hardware

### ISSUE THREAD

**Issue by obilodeau** [joukewitteveen/netctl#121]
Ultra slim laptops don't carry ethernet ports anymore. A USB to Ethernet dongle is required for wired networking.

netctl-ifplugd systemd service will stop if the underlying hardware cannot be found:

```
systemd[1]: sys-subsystem-net-devices-dongle0.device: Job sys-subsystem-net-devices-dongle0.device/start timed out.
systemd[1]: Timed out waiting for device sys-subsystem-net-devices-dongle0.device.
systemd[1]: Dependency failed for Automatic wired network connection using netctl profiles.
systemd[1]: netctl-ifplugd@dongle0.service: Job netctl-ifplugd@dongle0.service/start failed with result 'dependency'.
systemd[1]: sys-subsystem-net-devices-dongle0.device: Job sys-subsystem-net-devices-dongle0.device/start failed with result 'timeout'.
```

Even if you plug back the dongle in you need to start the netctl-ifplugd service in order for automatic network to work. No longer automatic.

**Comment by joukewitteveen** [comment]
I think you should write a udev rule that starts the netctl-ifplugd service when the dongle is plugged in.
More information on this topic is available in the `systemd.device(5)` manpage and (as I found by searching the web) in the [CoreOS documentation](https://coreos.com/os/docs/latest/using-systemd-and-udev-rules.html).
