### ISSUE TITLE
Use same dhcpcd instance for both IPv4 and IPv6

### ISSUE THREAD

**Issue by SammysHP** [joukewitteveen/netctl#122]
- WLAN via netctl-auto
- IPv4/IPv6 dual stack
- Want to use [RFC 7217](https://tools.ietf.org/html/rfc7217)

By default (`IP6=`) no privacy extension is used (if not enabled via sysctl `net.ipv6.conf.all.use_tempaddr=2`). AFAIK the kernel implements basic [RFC 4941](https://tools.ietf.org/html/rfc4941) which is ok, but not perfect. RFC 7217 seems to be better (but I'm not an expert).
AFAIK dhcpcd is the only program at the moment that implements RFC 7217. I used it already with a wired interface (without netctl but simple `dhcpcd@.service`) and it worked fine.

netctl is able to use dhcpcd for IPv6 configuration:

```
IP=dhcp
IP6=dhcp
DHCP6Client=dhcpcd
```

I haven't tested if it works stable, but in the short period I'm using it it works fine. The problem is, that this combination starts two dhcpcd instances:

```
   CGroup: /system.slice/system-netctl\x2dauto.slice/netctl-auto@….service
           ├─3418 wpa_supplicant -q -B -P /run/wpa_supplicant_…
           ├─3420 wpa_actiond -p /run/wpa_supplicant -i …
           ├─3445 dhcpcd -4 -q -t 30 -K -L …
           └─3478 dhcpcd -6 -q -t 30 …
```

I suggest to add an option to use dhcpcd for both IPv4 and IPv6 (e.g. as `dhcpcd -q -t 30 -K -L …`).

Btw: What is the difference between `IP6=` and `IP6=stateless`? (I assume that it does nothing and the only reason that I got an IPv6 address is because the kernel did it automatically.)

**Comment by joukewitteveen** [comment]
Having separated instances of the dhcp client for IPv4 and IPv6 makes the netctl source simpler. Is there a technical reason for wanting to have one instance for both?

**Comment by SammysHP** [comment]
To be honest, I don't know anymore if there is any technical reason (except for minimal less RAM usage). This was more than a year ago. I think it was just a cosmetical issue.

**Comment by joukewitteveen** [comment]
I agree that it is somewhat more beautiful in most cases, but the RAM savings are not worth the extra code: netctl depends on bash and systemd so it doesn't run on super-tight embedded systems anyway :-(.
