### ISSUE TITLE
netctl tries to connect to non-existing profile

### ISSUE THREAD

**Issue by theSage21** [joukewitteveen/netctl#123]
I once had a wireless profile registered in my system by the name `wlo1-Gauri`.  
This profile does not list under `netctl-auto list` and `netctl list` both as my normal account and as root.  
However, during boot I find that netctl is trying to connect to this profile and I have no idea why. Here is the output of `systemctl status netctl@wlo1\\x2dGauri` which exits with return code 3.

```
● netctl@wlo1\x2dGauri.service - Networking for netctl profile wlo1-Gauri
   Loaded: loaded (/usr/lib/systemd/system/netctl@.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2015-11-24 12:29:52 IST; 9min ago
     Docs: man:netctl.profile(5)
 Main PID: 326 (code=exited, status=1/FAILURE)

Nov 24 12:29:51 archer systemd[1]: Starting Networking for netctl profile wlo1-Gauri...
Nov 24 12:29:51 archer network[326]: Profile 'wlo1-Gauri' does not exist or is not readable
Nov 24 12:29:52 archer systemd[1]: netctl@wlo1\x2dGauri.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 12:29:52 archer systemd[1]: Failed to start Networking for netctl profile wlo1-Gauri.
Nov 24 12:29:52 archer systemd[1]: netctl@wlo1\x2dGauri.service: Unit entered failed state.
```

If I try to disable the profile with `netctl disable wlo1-Gauri` it prints out `No regular unit file found for profile 'wlo1-Gauri'`. I have tried creating a dummy profile in `/etc/netctl/` but when I do that netctl itself does not start and I lose wireless connectivity.

My wireless works fine without the `wlo1-Gauri` profile but it is kind of irritating to see `[Failed]` everytime I start my laptop.

**Comment by joukewitteveen** [comment]
Use `netctl disable wlo1-Gauri` to delete the leftover unit file. The problem probably started when you removed the profile file of an enabled profile.

**Comment by theSage21** [comment]
@joukewitteveen as I mentioned, I tried that but the problem persists. Here is what I do.

```
✓ arjoonn ~ $netctl disable wlo1-Gauri
netctl needs root privileges
1 arjoonn ~ $sudo netctl disable wlo1-Gauri
[sudo] password for arjoonn: 
No regular unit file found for profile 'wlo1-Gauri'
✓ arjoonn ~ $sudo su
[root@archer arjoonn]# netctl disable wlo1-Gauri
No regular unit file found for profile 'wlo1-Gauri'
[root@archer arjoonn]# exit
✓ arjoonn ~ $
```

Despite this on my next boot, the message is still there.

**Comment by joukewitteveen** [comment]
What does `systemctl list-dependencies --reverse netctl@wlo1-Gauri` give you?

**Comment by theSage21** [comment]
`netctl@wlo1-Gauri.service`

**Comment by joukewitteveen** [comment]
`find /etc/systemd/system/ -name netctl\*`?

**Comment by theSage21** [comment]
```
/etc/systemd/system/multi-user.target.wants/netctl-auto@wlo1.service
/etc/systemd/system/multi-user.target.wants/netctl@wlo1\x2dGauri.service
```

Should I delete that file?

**Comment by joukewitteveen** [comment]
Yes, but the weird thing is, that is precisely what `netctl disable wlo1-Gauri` is supposed to do. Anyway, delete it and be happy :-).

**Comment by theSage21** [comment]
Thanks. :smile:
