### ISSUE TITLE
Can't start network with Routes() defined

### ISSUE THREAD

**Issue by x89** [joukewitteveen/netctl#124]
The documentation seems to allude that one may set routes via the `Routes()` syntax, but whenever I do so I get the error:

``` error
Could not set gateway '192.168.0.1' on interface 'enp3s0'
Failed to bring the network up for profile 'ethernet'
```

The only difference is that in one file the `Routes=(…)` section is commented out (and thus it works).

``` bash
Description="Ethernet"

Connection=ethernet
Interface=enp3s0

IP=static
IP6=no
Address='192.168.0.42/24'
Gateway='192.168.0.1'
#Routes=('0.0.0.0/0 via 192.168.0.1')
#Routes=(
#  '0.0.0.0/0 via 192.168.0.1'
#  '146.66.0.0/16 via 192.168.0.1'
#  '132.185.112.0/20 via 192.168.0.1'
#  '132.185.0.0/16 via 192.168.0.1'
#  '212.58.224.0/19 via 192.168.0.1'
#  '132.185.128.0/20 via 192.168.0.1'
#)

Hostname="my.host.name"
TimeoutUp=2
```

Is this a bug or something in my configuration that I've missed?

**Comment by joukewitteveen** [comment]
Any news on this? I would guess that setting a route to `0.0.0.0` is not allowed.

**Comment by x89** [comment]
`0.0.0.0` would be null routing, `0.0.0.0/0` is all IPv4 space.

**Comment by joukewitteveen** [comment]
Still, all `netctl` does is basically
```
for route in "${Routes[@]}"; do
    ip route add $route dev "$Interface"
done
```
so I guess something in your configuration must be wrong.
Looking closer I see you try to set routes that run via the gateway. Netctl sets up the gateway after initializing the static routes. I would not be surprised if it doesn't like adding a gateway that is already present in the routing table. Why would you want to manually add routing information to the default gateway anyway?
