### ISSUE TITLE
profil works with netctl, but not with netctl-auto

### ISSUE THREAD

**Issue by Quardah** [joukewitteveen/netctl#127]
Hello,

I have a profile for netctl working if i use it manually with netctl, but it's not working using netctl-auto.

The wiki ([https://wiki.archlinux.org/index.php/Netctl#Automatic_switching_of_profiles](url)) says "Note that automatic selection of a WPA profile by netctl-auto is not possible with option Security=wpa-config, use Security=wpa-configsection instead."

And so i changed this line in my config file but it still fails to work properly.

Here is the content of my config file :

```
 Description='Automatically generated profile by wifi-menu'
 Interface=wlp3s0
 Connection=wireless
 Security=wpa-configsection
 ESSID=NetworkP
 IP=dhcp
 NETCTL_DEBUG=yes
 WPAConfigFile=/etc/wpa_supplicant/wpa_supplicant_networkp.conf

```
Here is the content of wpa_supplcant_networkp.conf :

```
ctrl_interface=/run/wpa_supplicant
update_config=1

network={
	ssid="NetworkP"
	scan_ssid=1
	key_mgmt=WPA-EAP
	eap=PEAP
	identity="mylogin"
	password="mypass"
	phase1="peaplabel=0"
	phase2="auth=MSCHAPV2"
}
```

When i run the switch-to command

```
$ sudo netctl-auto switch-to wlp3s0-NetworkP
WPA association/authentication failed for interface 'wlp3s0'
```

Somehow something fails with the association but it works with no issue using manual netctl (when i remove the "section").

Thanks

**Comment by smallst** [comment]
same here, even Security=none profile says 
WPA association/authentication failed for interface 'wlp3s0'

netctl works well, both start and switch-to, but netctl-auto doesn't work

**Comment by joukewitteveen** [comment]
As stated in `netctl.profile(5)`, profiles using `WPAConfigFile=` are excluded from automatic profile selection. This is a technical restriction. I am sorry.
If you want to use `Security=wpa-configsection`, you need to include a `WPAConfigSection=` block in your profile.
