### ISSUE TITLE
Trouble getting bond to work

### ISSUE THREAD

**Issue by s0nspark** [joukewitteveen/netctl#131]
Ok, let me preface by saying I'm probably doing something wrong. I'm very new to netctl ;-) This is on an up-to-date Arch Linux install. No other connection managers are installed or running.

My configs are documented here: https://gist.github.com/s0nspark/0ed0b3ea9548c79138fb

When I manually create the bond via the commands listed towards the end of the gist, it works... when I use netctl with the bonding profile, it does not. What am I missing?

Thanks!

**Comment by joukewitteveen** [comment]
Without journal output (preferably with netctl in debugging mode), it is hard to say anything. Additionally, this is not a support forum. Those are at https://bbs.archlinux.org/. You have better chances there.

**Comment by s0nspark** [comment]
Thanks for the tip about debug mode and the pointer to the Arch support forums.

I narrowed this down to netctl failing to bring up the bond if the bond device already existed. I was autoloading the bonding module at boot - removing that directive and letting netctl load the module on demand is working for me.

Is there a reason that netctl does not try to bring down the device first if it exists? I can understand not doing that with physical devices but with a virtual device like a bond it seems it would be... helpful.

**Comment by s0nspark** [comment]
One other observation... getting the profile 'just right' has been a challenge, especially with regard to what values need to be quoted. Trial and error got me there (e.g. Mode=820.3ad is not the same as Mode='802.3ad' - the latter works, the former is ignored...) but are there some general guidelines? Is it safe to quote all of the values?

**Comment by joukewitteveen** [comment]
I would guess this is because the former contains a typo.
Not bringing anything down is a safety precaution and it protects users from misconfiguring their systems (which happens more often than not when it is about networking). You are right that virtual devices might be a good exception to this rule, but I will not put any effort in making the logic more complicated by implementing this. Patches will be considered, but they must really show their added value.

**Comment by s0nspark** [comment]
No, that typo was mine - the conf file had it right, with one instance quoted and the other not. The profile is just sourced in the shell context netctl is run under,right? I'm using zsh and wondering if that makes any difference...

Understood about the safety precaution and the desire to keep the logic clean... I may work on a patch if I see any value going forward. The bulk of my troubles seemed to have stemmed from bad Internet info regarding autoloading the module and now that it is working, well, I know better. :)

**Comment by joukewitteveen** [comment]
You are correct: the profile is sourced, so in this case it should not matter whether the value is quoted or not. The script is run in bash, regardless your login shell so unless your `/bin/bash` points to zsh, it should `just work'.

**Comment by s0nspark** [comment]
OK - got it. :) Thanks again for the help and info!
