### ISSUE TITLE
Support for UTF-8 encoded SSID

### ISSUE THREAD

**Issue by armaab** [joukewitteveen/netctl#132]
When connect to wifi, if ssid contains unicode characters, it cannot be shown correctly.

**Comment by joukewitteveen** [comment]
That is because an ssid is a string of bytes without reference to any encoding. I am afraid this cannot be fixed. The quoting rules of netctl already make it possible to connect to ssids with characters outside the ascii printable range. I do not know of anything more powerful that we could do.

**Comment by armaab** [comment]
Well, I will close this issue.

**Comment by armaab** [comment]
From [wikipedia](https://en.wikipedia.org/wiki/Service_set_(802.11_network)#Service_set_identification_.28SSID.29) I found this: Note that the 2012 version of the 802.11 standard defines a primitive SSIDEncoding, an Enumeration of UNSPECIFIED and UTF-8, indicating how the array of octets can be interpreted.

**Comment by joukewitteveen** [comment]
Note (to self): UTF-8 encoding can be inferred when the `UTF-8 SSID` field of the extended capabilities is set (802.11 page 566). Support for this field must be streamlined with `wpa_supplicant`.

**Comment by NamPNQ** [comment]
Any update about this issue?

**Comment by joukewitteveen** [comment]
As far as I can tell `wpa_supplicant` does not advertise extended capabilities. Support in `hostapd` was added in b93c8509cc4e748d441676f59577e346cea5db29 at the end of 2012, but `wpa_supplicant` appears to ignore them.

If at some point `wpa_supplicant` picks up support for advertising extended capabilities, let me know and I might look into it.

**Comment by NamPNQ** [comment]
@joukewitteveen I see someone convert ssid to bytes, it's work with `wpa_supplicant`

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=134358

**Comment by joukewitteveen** [comment]
That is already supported since the very first version of netctl 4 years ago via the special quoting rules (see `netctl.profile(5)`). In fact, support in `wpa_supplicant` for escape sequences was developed in conjunction with the netctl special quoting rules.

The current bug is about proper UTF-8 detection and support.

**Comment by NamPNQ** [comment]
@joukewitteveen Why we do not convert all (both not utf-8 and utf-8) by default?

**Comment by joukewitteveen** [comment]
Because that would be in violation of the 802.11 specification. We need support for arbitrary byte strings. The difficulty is in deciding which byte strings are really UTF-8 strings. As said before, the specification gives one way to communicate that the SSID is UTF-8, yet this is not currently relayed by `wpa_supplicant`.

**Comment by armaab** [comment]
I think it's more user frinedly if we try to decode SSID as UTF-8 whenever it can successfully be decoded in UTF-8(though it's definitely not easy to do so using shell scripts). According to my experiment, many APs simply do not set that bit even if the SSID is indeed encoded in UTF-8.

**Comment by joukewitteveen** [comment]
Here you go: e4638274ac7f84b749cdcbd8e93f06a5564280e7 :-).
@armaab: Apparently, I had to come to that conclusion myself before implementing support.
I agree that this has taken a bit too long. Thanks for your patience!

More info on the related bug on the official bug tracker:
https://bugs.archlinux.org/task/45384
