### ISSUE TITLE
Issues with vlan-interfaces... (Interface exists)

### ISSUE THREAD

**Issue by RubenKelevra** [joukewitteveen/netctl#136]
I had an issue with the first start of a vlan-interface. Now every restart failed, because the interface already exists...

Normally I would expect that that the interface will be deleted if I select restart and a start is not possible because the interface already exist.

`network[21337]: Starting network profile 'lan-bond.30'...`
`network[21337]: Interface 'lan-bond.30' already exists`
`network[21337]: Failed to bring the network up for profile 'lan-bond.30'`
`systemd[1]: netctl@lan\x2dbond.30.service: Main process exited, code=exited, status=1/FAILURE`
`systemd[1]: Failed to start Virtual LAN 30 on interface lan-bond.`

**Comment by k0ste** [comment]
@RubenKelevra, add ForceConnect & SkipNoCarrier options. This is reflected in man.

**Comment by joukewitteveen** [comment]
It is quite hard to clean up properly on failure. Current connection types hardly implement any rollback. Indeed, this could be improved. Patches are very welcome.

For a practical workaround, the suggestion of @k0ste should work.

**Comment by RubenKelevra** [comment]
Actually this won't work:

I've created the interface with a bug in the config, I've added a existing gateway, which was denied by "already exist".

So I fixed it, but the interface now already exists. When I stop the interface it is not deleted, when I restart it it's failed because it's already exists. So my point is, add the check for "existing" to *stop* like on start and delete the interface then. Also do the same on restart, so the user can cleanup with netctl rather than fixing it by hand.

**Comment by joukewitteveen** [comment]
The interface is deleted when the profile is stopped, but stopping a failed profile is a nop. This is the same for systemd units in general.
In some situations, rollback is undesirable since it makes debugging harder. As I said, there is room for more 'clear on failure' code, but this is not easy. Conceivably, we can have `ForceConnect` override some more checks.
