### ISSUE TITLE
Restart via Systemd?

### ISSUE THREAD

**Issue by RubenKelevra** [joukewitteveen/netctl#138]
What about adding 

`RestartPreventExitStatus=15 1`

to /usr/lib/systemd/system/netctl@.service? :)

Actually I've ran in the issue with an PPPoE connection... which exits with "1" or "15".

The restart is stopping now only with 
```
Starting network profile 'eth0_wan'...
The interface of network profile 'eth0_wan' is already up
```

**Comment by joukewitteveen** [comment]
What about it? Do we tap into systemd restart logic anywhere?

**Comment by RubenKelevra** [comment]
This would check the "oneshot" for errorcodes on startup and would do a restart when the startup failed.

**Comment by joukewitteveen** [comment]
So you mean `RestartForceExitStatus=`? It is very unlikely that a restart will succeed if the original start did not, right? When I am messing with DHCP servers or wifi antennas, I sometimes find myself doing
```
# until netctl restart <profile>; do :; done
```

**Comment by RubenKelevra** [comment]
actually I don't want to drive to the location because the router has rebooted and the dsl uplink is not ready fast enough to satisfy netctl.

When I enable an pppoe link I expect reconnect tries as long as I didn't disable it. Not waiting 60 seconds and fail permanently.

Currently the `RestartPreventExitStatus=15 1` wouldn't work fully because the eth0 is still "up".

Actually a bit strange when I type something like:

`netctl start ppp0 `

which failed, then I retry it:

`netctl start ppp0 `

and getting

```
Starting network profile 'ppp0'...
The interface of network profile 'ppp0' is already up
```

Which has to be fixed manually

**Comment by joukewitteveen** [comment]
You still mean `RestartForceExitStatus=`, right? It looks like your real bug is that the timeout should be longer. A timeout should really be indicative of a failed state and as I said before: recovery on failure is hard, especially when you want transparent debugging. Patches to improve rollback are welcome. Patches to add `RestartForceExitStatus=` will not be taken. You can always add them in the ways provided by systemd to extend the configuration of services.

**Comment by RubenKelevra** [comment]
Actually the DSL is currently broken since 3 days. So for me a timeout for a "persistent" connection is not  reasonable. If a dialup is currently not available would expect a constant retry like every router does. A crashed service which needs manual cleanup is a no-go.

**Comment by joukewitteveen** [comment]
Can you test [this](https://gist.github.com/joukewitteveen/55b6f2931384af74aec15f1a3b72c2cf) as a drop-in replacement for `/usr/lib/network/connections/pppoe`? It should make it possible to restart the profile on failure without manual intervention.

**Comment by joukewitteveen** [comment]
e4554f2b9f0a274c2d06e218bf11e7c555b3ace9
