### ISSUE TITLE
netctl-auto current command

### ISSUE THREAD

**Issue by fbanfi90** [joukewitteveen/netctl#139]
I am really missing the command "netctl-auto current", since the goal of the last commit was "getting commands to be uniform between netctl and netctl-auto", why instead of removing the "current" command from netctl-auto, not add it to netctl?

Since I have many profiles saved, when I want to know to which WiFi I am currently connected (e.g. at school, where there are more than just one), I find the command "netctl-auto current" much more elegant than "netctl-auto list".

**Comment by joukewitteveen** [comment]
How about adding
```
alias netctl-auto-current='netctl-auto list | sed -n "s/^\* //p"'
```
to your `.bashrc`?

**Comment by fbanfi90** [comment]
Exactly what I did ;) thanks
