### ISSUE TITLE
Remove network.target from Before in netctl@.service

### ISSUE THREAD

**Issue by boustrophedon** [joukewitteveen/netctl#140]
There may be reasons for network.target in netctl@.service's Before=, but on my systems it slows down boot. I don't recall when this started occurring, but currently my laptop will wait for the network to come up before launching X and my window manager. On a laptop this causes two problems: one, connecting to wifi is relatively slow; and two, if I reboot and I can't connect to the network I have enabled, boot simply hangs while it tries to connect to a non-existent network.

I have tested removing network.target from Before= in netctl@.service (but not from the Wants= line!) and it appears to do what I want: X and my display manager start, and at the same time it is attempting to connect to the network, and succeeds. But my system is still usable while it is attempting to connect.

**Comment by joukewitteveen** [comment]
Yes, this will be present in the next version of `netctl` although doing this right is a lot more involved than just removing that line. We will supply a `netctl-wait-online` service, among other things.
