### ISSUE TITLE
How to add a default route?

### ISSUE THREAD

**Issue by IsaacG** [joukewitteveen/netctl#141]
I need to add a default route after bringing up my connection, eg:
ExecUpPost='ip route add default via 192.168.2.1 dev enp6s0 src 192.168.2.50'

Is there a "more correct" way to do this using the Routes=()? The docs imply the format that Routes=() takes is limited and doesn't support default routes.

**Comment by joukewitteveen** [comment]
Gateways can be configured using `Gateway=` and otherwise you can indeed use `Routes=()`.

**Comment by IsaacG** [comment]
I hadn't realized that "gateway" and "default route" meant the same thing. Thanks!
