### ISSUE TITLE
There is no internet after turning off and turning on hardware button on my laptop

### ISSUE THREAD

**Issue by 414d** [joukewitteveen/netctl#142]
The subject is for this command 
`systemctl start netctl-auto@your_interface.service`
I found the reason of the subject. netctl-auto starts dhcpcd with the key -K. To fix this problem you have to  remove this key from options of dhcpcd. By the way netctl starts dhcpcd without the key -K.
Here are options for dhcpcd which started by netctl:
`dhcpcd -4 -q -t 30 -L your_interface`
Here are options for dhcpcd which started by netctl-auto:
`dhcpcd -4 -q -t 30 -K -L your_interface`
Why did you add -K for netctl-auto?
Could you remove this key from your code (I guess the key -K is here: auto.action) or could you add the ability to modify dhcpcd command line options?

**Comment by joukewitteveen** [comment]
The `-K` switch goes back to [this](https://lists.archlinux.org/pipermail/arch-projects/2012-March/002673.html) netcfg patch. Does your lease timeout? In that case `wpa_actiond` should timeout too and register a disconnect, which, when reconnecting, should cause `dhcpcd` to be restarted.

It would be nice if you can verify that `dhcpcd` is properly stopped when the lease timeout occurs. You could add `NETCTL_DEBUG=yes` to your profile for this and inspect the journal.

A workaround would be to use `dhclient` for your `netctl-auto` profiles.
