### ISSUE TITLE
Is there quick a way to stop all running profiles and then start a certain one?

### ISSUE THREAD

**Issue by fschr** [joukewitteveen/netctl#146]
I use netctl and frequently switch between two profiles. This leads to my shell auto-completing like so (the auto-completed part is in square brackets):

* when I am running profile A and I want to run profile B instead

`$ netctl s[tart A]`

* when I am running profile B and I want to run profile A instead

`$ netctl s[tart B]`

As you can see, my shell's auto-complete guesses the exact opposite of what I want to do: in order to stop using A and start using B, I have to type `netctl stop A` followed by `netctl start B`. This is more tedious than needs to be, especially when `A` and `B` are longer names.

It would be nice to be able to just run `netctl switch A`, which would stop all running profiles and then attempt to start A. Is this feature built into `netctl`? Should I just write a script myself?

**Comment by joukewitteveen** [comment]
You mean the `switch-to` subcommand? Have you checked the netctl manpage?

**Comment by fschr** [comment]
facepalm. I have not checked the man page. Thanks.
