### ISSUE TITLE
netctl stop-all exits with error status when there are no profiles

### ISSUE THREAD

**Issue by d3dave** [joukewitteveen/netctl#150]
If there are no profiles, `netctl stop-all` will always exit with a status of 1 instead of 0, indicating an error.
[Link to line in question](https://github.com/joukewitteveen/netctl/blob/master/src/netctl.in#L67)
The condition does not hold so bash returns 1 from the function. Perhaps there should be an explicit `return 0` in case there are no profiles?

The default vm suspend script in open-vm-tools calls `netctl stop-all` and returns it's exit code. If it's 0, VMware Workstation suspends the VM without issue. In this case, the exit code is 1, and VMware Workstation pops up an error message saying there was an error while suspending.

**Comment by joukewitteveen** [comment]
Thanks, good catch! I'll change this line and the similar one in `switch_to()` to full `if` statements in the next version of `netctl`.

**Comment by joukewitteveen** [comment]
17cbd88d67775f931aae5819a253d3b1d578972e
