### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by derpyderpaderp** [joukewitteveen/netctl#152]
I am experiencing a bug or something. For some reason I have a exclamation point next to the Wi-Fi symbol in the panel. I have tried sudo systemctl restart NetworkManager.service to see if this would clear it out and it did for a minute then came back. I then diconnected from the wifi and still nothing. Is their something I can do to fix this issue? I have looked this up and I cannot seem to find a fix for it. Any help would be appreciated. Thanks! Edit: I am using Arch linux with the latest lts kernel on KDE if that is any help.

**Comment by joukewitteveen** [comment]
You have found your way to the issue tracker on the GitHub [mirror](https://git.archlinux.org/netctl.git/) of `netctl`. However, you are requesting help with (apparently) `NetworkManager`.

For help, please turn to the [support channels of your distribution](https://bbs.archlinux.org/). Please realize that `netctl` and `NetworkManager` are two different pieces of software. You should choose either one of them to manage your connection, but not both. When seeking help, state which software you have chosen to use (and maybe also why).
