### ISSUE TITLE
netctl-auto doesn't like hyphens in the profile name

### ISSUE THREAD

**Issue by rmasp98** [joukewitteveen/netctl#155]
I think netctl-auto falls over if one of the profiles has a hyphen in it. I think the problem arises in the service it tries to generate but don't know too much about it. Let me know what information you need to track this down

**Comment by joukewitteveen** [comment]
I see no reason why profile names with hyphens should cause problems. Can you give some steps to reproduce your problem?

**Comment by kovetskiy** [comment]
btw, wifi-menu generates profile names with hyphen as joiner between interface and wifi point name, like `wlp58s0-FreeWifi`.

I have not seen any problems with it.

**Comment by rmasp98** [comment]
Sorry I should be more explicit. I meant an additional hyphen to the one made by wifi-menu, e.g my WiFi might be called wi-fi so the profile generated is called wlp1s0-wi-fi. This causes netctl-auto to crash at start up for some reason. When I remove the second hyphen (wlp1s0-wi-fi) it works fine. I will try and reproduce the issue again when I'm next in my laptop

**Comment by joukewitteveen** [comment]
Thanks @kovetskiy for chiming in!
I cannot reproduce the issue either, even when I rename my profile to `wlp1s0-wi-fi`.

**Comment by rmasp98** [comment]
Apparently it has decided to not let me recreate the issue anymore... Sorry for wasting your time!
