### ISSUE TITLE
netctl-auto@interface.service is not started after interface is inserted

### ISSUE THREAD

**Issue by alex3kov** [joukewitteveen/netctl#159]
I use USB WiFi dongle which I plug and unplug regularly. On unplugging, netctl-auto reacts intelligently by stopping wpa_actiond:
```
Aug 18 08:40:06 arch wpa_actiond[1366]: Interface 'wlp0s20u1' lost connection to network 'Keenetic-4869'                                
Aug 18 08:40:06 arch systemd[1]: Stopping Automatic wireless network connection using netctl profiles...
Aug 18 08:40:06 arch wpa_actiond[1366]: Interface 'wlp0s20u1' disconnected from network 'Keenetic-4869'                                 
Aug 18 08:40:06 arch dhclient[2876]: Killed old client process
Aug 18 08:40:07 arch wpa_actiond[1366]: Terminating wpa_actiond session for interface 'wlp0s20u1'
Aug 18 08:40:08 arch netctl-auto[2857]: /usr/lib/netctl/interface: line 42: /sys/class/net/wlp0s20u1/flags: No such file or directory
Aug 18 08:40:18 arch systemd[1]: Stopped Automatic wireless network connection using netctl profiles.
```
But when I plug WiFi dongle back in, netctl-auto remains inactive, so I have to start it again as root:
```
~: systemctl status netctl-auto@wlp0s20u1.service 
● netctl-auto@wlp0s20u1.service - Automatic wireless network connection using netctl profiles
   Loaded: loaded (/usr/lib/systemd/system/netctl-auto@.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Sat 2018-08-18 08:40:18 MSK; 47s ago
     Docs: man:netctl.special(7)
  Process: 2934 ExecStopPost=/usr/bin/netctl-auto clean wlp0s20u1 (code=exited, status=0/SUCCESS)
  Process: 2857 ExecStop=/usr/bin/netctl-auto stop wlp0s20u1 (code=exited, status=0/SUCCESS)

Aug 18 08:40:07 arch dhclient[2876]: exiting.
Aug 18 08:40:07 arch wpa_actiond[1366]: Terminating wpa_actiond session for interface 'wlp0s20u1'
Aug 18 08:40:08 arch netctl-auto[2857]: /usr/lib/netctl/interface: line 42: /sys/class/net/wlp0s20u1/flags: No such file or directory
Aug 18 08:40:18 arch systemd[1]: Stopped Automatic wireless network connection using netctl profiles.
```
It would be cool if netctl reacted to appearance of physical WiFi interface by starting up corresponding netctl-auto@interface.service.

**Comment by joukewitteveen** [comment]
Could this be solved by a udev rule that starts the `netctl-auto@<interface>.service` service when the device (re)appears? I am thinking about something along the lines of [this](https://coreos.com/os/docs/latest/using-systemd-and-udev-rules.html).

If so, the question becomes whether netctl should be taught to write such rules.

**Comment by alex3kov** [comment]
> If so, the question becomes whether netctl should be taught to write such rules.

Sounds reasonable, since netctl is already tied to systemd, udev is a part of systemd and seems to integrate nicely with systemd units.  
I'll fiddle with this in the near future, see what I can come up with. What is the contribution process for netctl? Do you review PRs here or do I send patches somewhere?

**Comment by alex3kov** [comment]
`udev` works, added a [tip to the Wiki](https://wiki.archlinux.org/index.php/Netctl#Starting_netctl-auto_on_insertion_of_pluggable_WiFi_module_.28usually_USB.29).

**Comment by joukewitteveen** [comment]
I opened systemd/systemd#10406. Let's see if it yields anything.

**Comment by joukewitteveen** [comment]
Maybe there is a simple solution after all.

Can you tell me what happens when you do the following?

1. Disable/remove all udev rules you have added
2. Disable the `netctl-auto` unit (`systemctl disable netctl-auto@wlp0s20u1`)
3. Change the last line of `/usr/lib/systemd/system/netctl-auto@.service` to
```
WantedBy=sys-subsystem-net-devices-%i.device
```
4. Execute `systemctl daemon-reload`
5. Reenable the `netctl-auto` unit (`systemctl enable netctl-auto@wlp0s20u1`)
6. Test whether `netctl-auto` is now started and stopped correctly on plugging and unplugging the device

**Comment by joukewitteveen** [comment]
d511899a3763c07420aa91b106354c8265c6e989 is part of netctl 1.19.
