### ISSUE TITLE
[Feature request] Auto retry wifi connection

### ISSUE THREAD

**Issue by desbma** [joukewitteveen/netctl#164]
Hello,

I have Wifi card that is a bit unreliable, and sometimes connection to Wifi succeeds but sometimes not.

When it fails to connect, I usually do `netctl restart PROFILE` until it succeeds.

I would like to automatically retry connection.

Currently I managed to do it by creating a systemd file in `/etc/systemd/system/netctl@PROFILE.service.d/auto_retry.conf` with:
```
[Service]
RestartForceExitStatus=1
RestartSec=5
```

`RestartForceExitStatus=1` allows restarting only if the profile failed to connect, but not if it crashed of got killed. `RestartSec=5` avoids restarting too quickly.

It does exactly what I want but is a bit "intrusive", and I should not have to alter internal netctl service files.

It would be great if netctl profile had an option to auto retry connection for that purpose.

Thanks

EDIT: I saw #69 but did not find an option like `TimeoutWPA` that would allow retries.

**Comment by joukewitteveen** [comment]
Hi,

If I understand your problem correctly, a fix in netctl would really be a workaround for a driver bug. I would rather not carry such code and suggest to report your issue with the driver maintainers.
Other than that, your `.d/auto_retry.conf` solution looks very clean to me!

That said, we could implement some retry-logic, but I am not convinced your use-case is enough of a rationale for this. If you think it is, please give some more background to your situation (beware that I may not be convinced).

Thanks you for your understanding.

**Comment by desbma** [comment]
I don't know `netctl-auto`. Is it to automatically change profile if a new network device is detected, or to automatically change access point if one is not reachable?

My use case is a static HTPC with good wifi signal (the router is maybe 15 meters away). 
On my laptop I use NetworkManager + IWD (just got rid of WPA supplicant).

**Comment by joukewitteveen** [comment]
Indeed, that is what netctl-auto does. If there is only one profile, then it behaves the way you want: when the connection drops, it tries to reestablish it.

In such a static case, you could also just configure the wpa_supplicant service and a dhcp service. Currently, the tried-and-tested wpa_supplicant may be easier to use than IWD.
