### ISSUE TITLE
Add option for accept_ra value

### ISSUE THREAD

**Issue by aeris** [joukewitteveen/netctl#165]
Currently, `accept_ra` is [only settable to 0 or 1](https://github.com/joukewitteveen/netctl/blob/master/src/lib/ip#L54), given `IP6` is `static` or not.
But `accept_ra` [can be set to 2](https://github.com/torvalds/linux/blob/master/Documentation/networking/ip-sysctl.txt#L1537) to enable RA even if the interface accept forward too.
Could it be possible to add an option to specify the `accept_ra` value?

**Comment by joukewitteveen** [comment]
Do you have a use-case for this? I'm okay with adding such options, but would prefer to give them more meaningful names.

**Comment by aeris** [comment]
Use case : my gateway :joy: 
`enp1s0` interface has forwarding enabled because it's the LAN/VPN/LXC gateway, and in this case, `accept_ra=1` is not enough to have SLAAC working on it and so `netctl` doesn't assign IPv6.
There is another case [here](http://strugglers.net/~andy/blog/2011/09/04/linux-ipv6-router-advertisements-and-forwarding/).

**Comment by joukewitteveen** [comment]
I have to think about this a bit and am very much pressed for time right now, I am sorry.
I will be sure to address this before the next version of `netctl`.

`AcceptRA=` would be the obvious candidate, but I do not like the value `2`. It does not convey what is happening. `AcceptRA=always` would be more readable, for example. However, what would we call the value `1`?

**Comment by joukewitteveen** [comment]
I gave it a little thought and see no reason why `netctl` should not just set `accept_ra` to `2` instead of to `1`. Can you think of any situation where you use `netctl` and `1` is preferred over `2`?

Replacing `$?` by `$((2*$?))` on line 54 of `/usr/lib/netctl/ip` should do the trick (although I will eventually expand this into a proper if statement).

**Comment by aeris** [comment]
At this moment I see no reason, but if there is 3 possible values in the kernel, it should have at least one :joy:

**Comment by joukewitteveen** [comment]
162af2a44bc3eac92929f396ca8950eb9b736975
