### ISSUE TITLE
Support stable private IPv6 addresses

### ISSUE THREAD

**Issue by michaelbeaumont** [joukewitteveen/netctl#166]
Aka [RFC7217](https://tools.ietf.org/html/rfc7217), supported for example in NetworkManager

**Comment by joukewitteveen** [comment]
Could you give some more details? When would this be most useful? How should this be configured without any network manager? A quick search revealed that `/proc/sys/net/ipv6/*/stable_secret` is the meat of the implementation of the RFC.

**Comment by michaelbeaumont** [comment]
I'm not totally sure myself how it's managed or implemented, but it appears to be implemented in the kernel with 
[`addr_gen_mode`](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt).

I don't think NetworkManager does it this way, seeing as how my NetworkManager interfaces are set `addr_gen_mode=1` and are nevertheless set using stable secret.

I'm not overly knowledgeable here, but can we just set `sysctl net.ipv6.conf.<if>.addr_gen_mode=3` on the interface?

**Comment by michaelbeaumont** [comment]
I originally asked because I hadn't found `addr_gen_mode` and knew that NM was setting it some other way. But setting `addr_gen_mode` to `2`/`3` for the entire interface works fine for me. I.e. my use case is covered without needing to change `netctl`.
I think your last point is important, profile specific settings are not the way to go 99% of the time.
