### ISSUE TITLE
NO SSID environment variable

### ISSUE THREAD

**Issue by zechfox** [joukewitteveen/netctl#172]
I use netctl with v1.20, and try to use a hook script to mount NFS depends on which wireless network I connected.
But it's failed to get SSID in hook script.
I use `ExecUpPost="printenv > /tmp/test" ` in script got no SSID, only following environment variables.
PWD=/
LANG=C
INTERFACE=wls3
INVOCATION_ID=493e6e4f0e4140a3b861396e891cb1fe
WPA_CTRL_DIR=/run/wpa_supplicant
WPA_ID_STR=wls3-zechfox@2.4G
SHLVL=2
WPA_ID=1
JOURNAL_STREAM=9:18334
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
ACTION=CONNECTED
_=/usr/bin/printenv

But #147 has show there's SSID in environment variable. Why it's gone in v1.20?
And how can I get SSID v1.20?
Thanks~

**Comment by joukewitteveen** [comment]
SSID should definitely be available, precisely for the things you are trying to do :-).
Can you check that it is definitely unavailable by replacing `printenv` by `set`? I would guess the variable is available, but simply not exported. In that case you can just use it, including exporting it if needed (`export SSID`).

**Comment by zechfox** [comment]
I use `ExecUpPost="set > /tmp/test"` in hook script, but I didn't got SSID as a variable.
Here is the output, I leave the function parts alone.
ACTION=CONNECTED
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=([0]="2")
BASH_ARGV=([0]="CONNECTED" [1]="wls3")
BASH_CMDS=()
BASH_LINENO=([0]="20" [1]="0")
BASH_SOURCE=([0]="/usr/lib/netctl/globals" [1]="/usr/lib/netctl/auto.action")
BASH_VERSINFO=([0]="5" [1]="0" [2]="7" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='5.0.7(1)-release'
Connection=wireless
DIRSTACK=()
Description='profile for zechfox@2.4G'
DhcpcdOptions=' -K -L'
EUID=0
ExecUpPost='set > /tmp/test'
FUNCNAME=([0]="do_debug" [1]="main")
GROUPS=()
HOSTNAME=zech-R61i
HOSTTYPE=x86_64
IFS=$' \t\n'
INTERFACE=wls3
INVOCATION_ID=e8eb09cd06e34229b264b7eac377018b
IP=dhcp
Interface=wls3
JOURNAL_STREAM=9:18043
LANG=C
MACHTYPE=x86_64-pc-linux-gnu
NETCTL_VERSION=1.20
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
PIPESTATUS=([0]="1")
PPID=375
PROFILE_DIR=/etc/netctl
PROFILE_FILE=/run/netctl/netctl-auto-wls3.profile
PS4='+ '
PWD=/
Profile=wls3-zechfox@2.4G
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=2
STATE_DIR=/run/netctl
STATE_FILE=/var/lib/netctl/netctl.state
SUBR_DIR=/usr/lib/netctl
Security=wpa-configsection
TERM=dumb
UID=0
WPAConfigSection=([0]="ssid=\"zechfox@2.4G\"" [1]="proto=RSN" [2]="key_mgmt=WPA-PSK" [3]="pairwise=CCMP TKIP" [4]="priority=1" [5]="psk=\":xxzgdnz:\"")
WPA_CTRL_DIR=/run/wpa_supplicant
WPA_ID=1
WPA_ID_STR=wls3-zechfox@2.4G
_='set > /tmp/test'

**Comment by zechfox** [comment]
I think this commit: https://github.com/joukewitteveen/netctl/commit/f2c3edb19eea8d3b8f5b61b8f9015a2db135a2f3 removed the SSID environment variable. 
Should I use wpa_supplicant to get the ssid of network instead of $SSID?

**Comment by zechfox** [comment]
I use ${WPA_ID_STR#*-} to get ssid to workaround the missing $SSID.

**Comment by joukewitteveen** [comment]
Hmm, this gets interesting. Indeed, the functionality got lost with f2c3edb19eea8d3b8f5b61b8f9015a2db135a2f3.

There are several ways to fix this. The backward compatible way would be something like adding
```
. "$SUBR_DIR/wpa"
export SSID=$(wpa_call "$INTERFACE" status | sed -n 's/^ssid=//p')
```
to `auto.action`. However, this `SSID=` variable is only available when using `netctl-auto`, and not when using a more manually controlled setup. Furthermore, the variable may be empty.

While I regret being backward-incompatible, I think the cleanest solution is to add
```
ESSID=zechfox@2.4G
```
to your profile. This variable is ignored by `netctl`, because you have `Security=wpa-configsection`. Nevertheless, it will be available for your hooks. Using `WPA_ID_STR=` will only give you the name of the profile, which is also available as `Profile=`.

Does this make any sense to you?

**Comment by zechfox** [comment]
For sure, I'll add ESSID in my profile. As you said, WPA_ID_STR has risk to get out SSID.
Thanks~
