### ISSUE TITLE
Only one hook works at a time

### ISSUE THREAD

**Issue by PonasKovas** [joukewitteveen/netctl#173]
When I have two files in `/etc/netctl/hooks` with different `ExecUpPost` and `ExecDownPre`, only one of them gets executed.

For example, I have:
`/etc/netctl/hooks/timesync`
```
ExecUpPost='/usr/bin/ntpd || true'
ExecDownPre='killall ntpd || true'
```
and
`/etc/netctl/hooks/notifications`
```
ExecUpPost="some complex command for notification"
ExecDownPre="some complex command for notification"
```
I don't get my notifications, but the `ntpd` service works as expected.

However, if I delete `/etc/netctl/hooks/timesync`, my notifications suddenly start working.

Is this expected behaviour?

**Comment by joukewitteveen** [comment]
Yes, this is expected behavior, as the timesync hook overwrites the value set by the notifications hook. You could get around this by changing the hooks into:
```
ExecSomething="some_command; ${ExecSomething}"
```
Note the `;` between the added command and the variable. This adds `some_command` before the commands that are already present.

**Comment by PonasKovas** [comment]
Hmm...

It still doesn't work

**Comment by PonasKovas** [comment]
For some reason this works:
```sh
ExecSomething="some command ; "$ExecSomething
```
