### ISSUE TITLE
When an issue occurs in the ISP, the systemd service of pppoe will fail.

### ISSUE THREAD

**Issue by onlymash** [joukewitteveen/netctl#184]
When an issue occurs in the ISP, the systemd service of pppoe will fail. After the ISP resolves the issue, the systemd service must be restarted manually.
This systemd service should remain in a waiting state, not failed

```
$ netctl status pppoe
× netctl@pppoe.service - wan0.2 PPPoE connection
     Loaded: loaded (/usr/lib/systemd/system/netctl@.service; enabled; vendor pres>
    Drop-In: /etc/systemd/system/netctl@pppoe.service.d
             └─profile.conf
     Active: failed (Result: exit-code) since Thu 2021-04-08 08:37:13 HKT; 1h 9min>
       Docs: man:netctl.profile(5)
    Process: 93928 ExecStart=/usr/lib/netctl/network start pppoe (code=exited, sta>
   Main PID: 93928 (code=exited, status=1/FAILURE)
        CPU: 53ms

Apr 08 08:36:08 arch-router network[93951]: Unable to complete PPPoE Discovery
Apr 08 08:37:13 arch-router pppd[93951]: Timeout waiting for PADO packets
Apr 08 08:37:13 arch-router network[93951]: Timeout waiting for PADO packets
Apr 08 08:37:13 arch-router pppd[93951]: Unable to complete PPPoE Discovery
Apr 08 08:37:13 arch-router network[93951]: Unable to complete PPPoE Discovery
Apr 08 08:37:13 arch-router pppd[93951]: Exit.
Apr 08 08:37:13 arch-router network[93928]: Could not establish a ppp connection f>
Apr 08 08:37:13 arch-router network[93928]: Failed to bring the network up for pro>
Apr 08 08:37:13 arch-router systemd[1]: netctl@pppoe.service: Main process exited,>
Apr 08 08:37:13 arch-router systemd[1]: netctl@pppoe.service: Failed with result '>

$ sudo netctl restart pppoe
$ netctl status pppoe
● netctl@pppoe.service - wan0.2 PPPoE connection
     Loaded: loaded (/usr/lib/systemd/system/netctl@.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/netctl@pppoe.service.d
             └─profile.conf
     Active: active (exited) since Thu 2021-04-08 09:47:27 HKT; 7s ago
       Docs: man:netctl.profile(5)
    Process: 103154 ExecStart=/usr/lib/netctl/network start pppoe (code=exited, status=0/SUCCESS)
   Main PID: 103154 (code=exited, status=0/SUCCESS)
     Status: "online"
      Tasks: 1 (limit: 9309)
     Memory: 828.0K
        CPU: 51ms
     CGroup: /system.slice/system-netctl.slice/netctl@pppoe.service
             └─103182 pppd file /run/netctl/pppoe-wan0.2-pppoe/options

Apr 08 09:47:27 arch-router network[103177]: peer from calling number CC:1A:FA:EA:0A:20 authorized
Apr 08 09:47:27 arch-router pppd[103177]: PAP authentication succeeded
Apr 08 09:47:27 arch-router pppd[103177]: peer from calling number CC:1A:FA:EA:0A:20 authorized
Apr 08 09:47:27 arch-router pppd[103177]: Cannot determine ethernet address for proxy ARP
Apr 08 09:47:27 arch-router network[103177]: Cannot determine ethernet address for proxy ARP
Apr 08 09:47:27 arch-router network[103177]: local  IP address 10.152.22.17
Apr 08 09:47:27 arch-router network[103177]: remote IP address 10.152.0.1
Apr 08 09:47:27 arch-router pppd[103177]: local  IP address 10.152.22.17
Apr 08 09:47:27 arch-router pppd[103177]: remote IP address 10.152.0.1
```

**Comment by joukewitteveen** [comment]
It looks like the failure of the service is due to a timeout on the side of `pppd` (`pppd[93951]: Timeout waiting for PADO packets`). Would your issue be solved if you increased the timeout?

**Comment by onlymash** [comment]
I don’t think this is the case. It can be seen from the log that pppd tried to connect several times and failed, and then stopped trying, and finally the service failed.

**Comment by onlymash** [comment]
The ideal state is triggered by a network request, which means that if the device has a network request, pppd will try to connect again

**Comment by joukewitteveen** [comment]
Not sure I understand what you mean. From your status output, I understand that `pppd` is the cause of the failed state. It exits unsuccessfully. Are you saying that `pppd` could do something else given some network communication? If so, what would such a configuration look like? If this is not yet implemented in `pppd`, should this issue maybe be reported there?

**Comment by onlymash** [comment]
Can netctl restart pppd after it fails?

**Comment by joukewitteveen** [comment]
Well, you could set `Restart=on-failure` on the systemd service (through a drop-in config file in `/etc/systemd/system/<your-unit>.d/<some-name>.conf`). That way, the entire netctl service will be restarted after `pppd` causes it to fail.

**Comment by onlymash** [comment]
Thanks for your suggestion, I have switched to systemd-networkd and rp-pppoe. customization is easier.

**Comment by joukewitteveen** [comment]
If you would be so kind, please share your configuration. Apparently I am missing something because a timeout is a timeout, right? Are you saying `systemd-networkd` never times out and simply keeps trying forever? Or is there something possible with PPP that I am unaware of?

**Comment by onlymash** [comment]
systemd-networkd does not support ppp, so I only use it to create interfaces and static IP.
finally use rp-pppoe dial-up.

 /etc/systemd/network/10-br-lan.netdev
```
[NetDev]
Name=br-lan
Kind=bridge
MACAddress=aa:bb:cc:dd:ee:48
```

/etc/systemd/network/11-br-lan-bind.network
```
[Match]
Name=lan*

[Link]
RequiredForOnline=no

[Network]
Bridge=br-lan
ConfigureWithoutCarrier=true
```

/etc/systemd/network/12-br-lan-bridge.network
```
[Match]
Name=br-lan

[Link]
RequiredForOnline=no

[Network]
ConfigureWithoutCarrier=true
Address=192.168.0.1/24
Address=fd00::1/64
```

/etc/systemd/network/20-wan0.network
```
[Match]
Name=wan0

[Link]
RequiredForOnline=no

[Network]
ConfigureWithoutCarrier=true
MACVLAN=wan0.1
MACVLAN=wan0.2
```

/etc/systemd/network/21-wan0.1.netdev
```
[NetDev]
Name=wan0.1
Kind=macvlan
MACAddress=aa:bb:cc:dd:ee:49

[MACVLAN]
Mode=bridge
```


/etc/systemd/network/22-wan0.2.netdev
```
[NetDev]
Name=wan0.2
Kind=macvlan
MACAddress=aa:bb:cc:dd:ee:4a

[MACVLAN]
Mode=bridge
```

/etc/systemd/network/23-wan0.1.network
```
[Match]
Name=wan0.1

[Link]
RequiredForOnline=no

[Network]
ConfigureWithoutCarrier=true
Address=192.168.200.2/24
```



install rp-pppoe
run pppoe-setup
copy /usr/lib/systemd/system/adsl.service to /etc/systemd/system/adsl.service
edit /etc/systemd/system/adsl.service
add After=systemd-networkd.service and Restart=on-failure
```
[Unit]
Description=ADSL Daemon
After=systemd-networkd.service

[Service]
Type=forking
ExecStart=/usr/bin/pppoe-start
ExecStop=/usr/bin/pppoe-stop
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by joukewitteveen** [comment]
Ah, so `Restart=on-failure` indeed did the trick. I'm happy you found something that covers your use case :-).
