### ISSUE TITLE
No way to leave resolv.conf alone with DHCP profile (?)

### ISSUE THREAD

**Issue by gkatev** [joukewitteveen/netctl#187]
Hi, I have a simple profile that uses DHCP. It looks like this:
```
Description='USB tether DHCP'
Interface=enp...
Connection=ethernet
IP=dhcp
DNS=()
```
The `DNS=()` part is because I'm trying it to get netctl/dhcpcd to not change my DNS settings in resolv.conf, but it does not work. I also tried not including the `DNS=` line at all, which is also not working, am I perhaps going about this wrong?

If I understand the code path correctly, I say there's no way to do what I need (not modify resolv.conf at all, when I strart the profile) because:

- If `$DNS` is undefined/empty, this won't trigger and the option to *not* replace resolv.conf won't be passed to dhcpcd: https://github.com/joukewitteveen/netctl/blob/9b70046f86b948c7e8c3c307f218c378714692ed/src/lib/dhcp/dhcpcd#L11-L12

- If `$DNS` is defined/non-empty, this will trigger and adjust resolv.conf: https://github.com/joukewitteveen/netctl/blob/9b70046f86b948c7e8c3c307f218c378714692ed/src/lib/ip#L161-L167

**Comment by joukewitteveen** [comment]
Hi! I think you could get what you want with
```
DhcpcdOptions="-L -C resolv.conf"
DhcpcdOptions6="-C resolv.conf"
```
in your profile. You may only need one of these lines (most likely the first one). The `DNS=()` line can be left out.

**Comment by joukewitteveen** [comment]
> Would it be best to add these options in the netctl.profile man page?

Yeah, that would be nice and I have thought of this before. There is a hint of these variables [under `DHCPClient=`](https://github.com/joukewitteveen/netctl/blob/1.28/docs/netctl.profile.5.txt#L172-L176). I thought there could be many more dhcp clients, so I didn't want to start listing all options back when I wrote that section. It seems there is little demand for additional clients, so feel free to make a suggestion for that part of the documentation. It's hard to get right, though: I don't want the section to be long and still it should be comprehensive. With that I mean that if it mentions one of these variables, it should mention all of them.

**Comment by gkatev** [comment]
Ah I see yes, I don't have any strong opinions. Perhaps a middleground might be to list 1-2 variable for each of the 1-2 most popular clients (so for dhcpcd: DhcpcdOptions and DhcpcdOptions6), and include a note that one should check the script of the specific client for a full list (?). Quick&dirty example scenario:

```
'DHCPClient=' [requires 'IP=dhcp']::
    The name of the DHCP client to use. By default, *netctl*
    comes with support for `dhcpcd' and `dhclient'. Defaults to
    `++dhcpcd++'.
    Clients may accept additional options through client-specific
    variables; these include `DhcpcdOptions' & `DhcpcdOptions6'
    for `dhcpcd', and `DhclientOptions' & `DhclientOptions6' for
    `dhclient'. Consult the script of the respective DHCP client
    for an exhaustive account of variables.
```
Indeed this does make the section notably longer in comparison. Feel free to go ahead (or not) any way you prefer (and to close this issue accordingly).

**Comment by joukewitteveen** [comment]
I've added a few lines of documentation in c1dd32216a83d09bce060daafe26edf267a47ae2. This will be part of the next release. It may take a while before sufficiently significant changes have piled up to warrant a new release, though. If things stay quiet for a long while, I may tag a new release with basically just this small update.
