### ISSUE TITLE
netctl start wireless-wpa-config fails

### ISSUE THREAD

**Issue by kaihendry** [joukewitteveen/netctl#81]
What am I doing wrong here?

http://ix.io/aXP

If I am using /etc/wpa_supplicant.conf as with the example https://github.com/joukewitteveen/netctl/blob/master/docs/examples/wireless-wpa-config do I need `sudo systemctl enable netctl-auto@wlan0.service`? Bit confused.

http://ix.io/aXQ

**Comment by nixn** [comment]
from http://ix.io/aXP:
```
[root@x220 netctl]# systemctl status netctl@wireless\x2dwpa\x2dconfig.service
netctl@wirelessx2dwpax2dconfig.service - Networking for netctl profile wirelessx2dwpax2dconfig
```

One has to escape the backslash in the shell (that hit me too some time):
`systemctl status netctl@wireless\\x2dwpa\\x2dconfig.service`
