### ISSUE TITLE
Bond: set mode

### ISSUE THREAD

**Issue by jsebosik** [joukewitteveen/netctl#96]
Hi,

I`ve made a tiny patch to netctl/src/lib/connections/bond, which allows user to configure bonding mode:

if is_interface "$Interface"; then
        report_error "Interface '$Interface' already exists"
        return 1
else
        interface_add bond "$Interface"
fi

+if [[ ! -z "$Mode" ]]; then
+echo $Mode > /sys/class/net/${Interface}/bonding/mode
+fi

bring_interface_up "$Interface"

Mode can be set according to kernel documentation: 
   https://www.kernel.org/doc/Documentation/networking/bonding.txt

**Comment by joukewitteveen** [comment]
Implemented in d2cf9ae99834de3b8338008cae6273b967c353cd
